--PARA TESTEAR--

SELECT * FROM GDD_15.DIRECCIONES -- 95 DIRECCIONES INSERTADAS--
SELECT * FROM GDD_15.USUARIOS --95 USU MIGRADOS + EL ADM CREADO --
SELECT * FROM GDD_15.CLIENTES --28 CLIENTES MIGRADOS--
SELECT * FROM GDD_15.EMPRESAS-- 67 EMPRESAS MIGRADAS--
SELECT * FROM #tmp_usuarios -- 95 USUARIOS MIGRADOS--
SELECT * FROM GDD_15.VISIBILIDADES -- 5 VISIBILIDADES INSERTADAS--
SELECT * FROM GDD_15.ROLES_USUARIOS --3 ROLES INSERTADOS--
SELECT * FROM GDD_15.FUNCIONALIDADES_ROLES --16 FUN_ROL INSERTADAS--
SELECT * FROM GDD_15.ROLES --3 ROLES INSERTADOS--
SELECT * FROM GDD_15.TIPOS
SELECT * FROM GDD_15.ESTADOS
-- NO HAY NADA TODAVIA-- LAS ESTOY MIGRANDO--
SELECT * FROM GDD_15.CALIFICACIONES 
SELECT * FROM GDD_15.OFERTAS
SELECT * FROM GDD_15.COMPRAS
SELECT * FROM GDD_15.RUBROS
SELECT * FROM GDD_15.PUBLICACIONES
GO

CREATE PROCEDURE GDD_15.AGREGARPUBLICACION @usuarioID BIGINT, @rubroID BIGINT, @visiID BIGINT, @estadoID BIGINT, @tipoID BIGINT, @descrip VARCHAR(100), @stock INT, @fecha_inicio DATETIME, @fecha_ven DATETIME, @precio FLOAT(24), @permite_envio VARCHAR(2), @opcion TINYINT 
AS
BEGIN
	DECLARE @visiDesc VARCHAR(50), @precioVisi FLOAT(24), @tipoDesc VARCHAR(50)
	SELECT @visiDesc = D_DESCRIP, @precioVisi = N_COMISION_PRECIO FROM GDD_15.VISIBILIDADES WHERE C_VISIBILIDAD = @visiID
	SELECT @tipoDesc = C_TIPO FROM GDD_15.TIPOS WHERE N_ID_TIPO = @tipoID
	IF (@opcion = 0)
	BEGIN
		INSERT INTO GDD_15.PUBLICACIONES(N_ID_USUARIO, N_ID_RUBRO, C_VISIBILIDAD, N_ID_ESTADO, N_ID_TIPO, D_DESCRED, N_STOCK, F_INICIO, F_VENCIMIENTO, N_PRECIO, C_PERMITE_ENVIO) VALUES (@usuarioID , @rubroID, + @visiID, @estadoID, @tipoID, @descrip, @stock, @fecha_inicio, @fecha_ven, @precio, @permite_envio)
	END
	ELSE IF  (@opcion = 1)
	BEGIN
		RAISERROR('Un Error',12,1)
	END
END;
GO