--PARA TESTEAR--

SELECT * FROM GDD_15.DIRECCIONES -- 95 DIRECCIONES INSERTADAS--
SELECT * FROM GDD_15.USUARIOS --95 USU MIGRADOS + EL ADM CREADO --
SELECT * FROM GDD_15.CLIENTES --28 CLIENTES MIGRADOS--
SELECT * FROM GDD_15.EMPRESAS-- 67 EMPRESAS MIGRADAS--
SELECT * FROM #tmp_usuarios -- 95 USUARIOS MIGRADOS--
SELECT * FROM GDD_15.VISIBILIDADES -- 5 VISIBILIDADES INSERTADAS--
SELECT * FROM GDD_15.ROLES_USUARIOS --3 ROLES INSERTADOS--
SELECT * FROM GDD_15.FUNCIONALIDADES_ROLES --16 FUN_ROL INSERTADAS--
SELECT * FROM GDD_15.ROLES --3 ROLES INSERTADOS--
